### ISSUE TITLE
Missing sdk lib in zip file

### ISSUE THREAD

**Issue by zljfdb** [DJI-Mobile-SDK-Tutorials/Android-PlaybackDemo#1]
Issue:
1. not found the SDK lib in zip file about "../SDK/DJI-SDK-A" defined in project.properties file
2. I tried reference SDK v2.4.0 lib for demo "Android-PlaybackDemo", but the interface dji.sdk.interfaces.DJIGerneralListener cannot be found in this version SDK.

So I think it is issue missing the specified SDK or the common SDK (v2.4.0) missing the interface for this demo application.

**Comment by mrjzhao** [comment]
1. Yes. Please use SDK v2.4.0 lib from dev.dji.com
2. Please correct DJIGerneralListener to DJIGeneralListener. and correct the corresponding imported package.

We have corrected the source code. You can repull it to update the code.

**Comment by dji-dev** [comment]
Close this issue now.
