### ISSUE TITLE
is it really not compatible to P3S ? 

### ISSUE THREAD

**Issue by luisreyesece** [DJI-Mobile-SDK-Tutorials/Android-PlaybackDemo#2]
i badly needed to know how to download the images from the drone to the android device , but the sample app given by dji only allows  single photo , i try creating a loop but it just download the recent one .. hope you can help , thanks a lot

**Comment by dji-dev** [comment]
Hi @LuisReyesJr , DJI Android SDK doesn't support DJIPlaybackManager on Phantom 3 Standard, you can use DJIMediaManager to download the images from the drone instead. Please check the **Media Download** in Camera component of [DJI Android SDK Sample Code](https://github.com/dji-sdk/Mobile-SDK-Android/tree/master/Sample%20Code) to learn how to use DJIMediaManager to download images.

BTW, the Android-PlaybackDemo use PlaybackManager to download images, which doesn't support Phantom 3 Standard, already mention in the Readme file.

**Comment by luisreyesece** [comment]
thanks a lot :) , we've figured it out and its now working
thanks

**Comment by dji-dev** [comment]
No problem, close the issue now.
